# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 임기호
title: 풀스택 개발자
email: Lasid84@naver.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: https://limgiho.github.io/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  limgiho
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
# about_profile_image: images/tulipBulbs.png
# about_content: | # this will include new lines to allow paragraphs
#   Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

#   You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#     - Lists
#     - Tables
#     - <a href="google.com">Links</a>
#     - Images ![alt text](/images/landscape-trees.jpg "Trees")

about_profile_image: images/tulipBulbs.png
about_content: | # this will include new lines to allow paragraphs
  NodeJS & TypeScript, C# & .NET 기반의 **14년차 풀스택 개발자**로, 제조∙물류 등 다양한 산업 분야에서 **웹과 데스크톱 애플리케이션** 개발을 주도해왔습니다.
  
  데이터 처리 자동화를 통해 **월 500시간 이상의 업무 절감**과 업무 처리 속도를 기존 10분에서 5초로 **120배 이상 향상**시키는 등 효율성 극대화에 강점이 있습니다.
  **레거시 시스템의 통합과 최적화** 경험이 풍부하며, Oracle, MySQL, PostgreSQL 등 다양한 데이터베이스 시스템을 능숙하게 관리하고 최적화할 수 있습니다.
  개인의 목표보다 **회사와 팀의 성장을 최우선**으로 생각하며, 사용자의 실제 업무 환경을 개선하고 효율성을 높이는 개발을 지향합니다.


content: 
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: (주)케이더블유이코리아
        link: https://www.kwe.com/
        link_text: www.kwe.com
        sub_title: 풀스택 개발자
        caption: 2022.01 ~ 현재
        quote: >
          연매출 2,634억원의 국제 종합 물류기업
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li><strong>10종의 레거시 시스템 및 3종의 DBMS</strong>를 분석∙파악 후 <a href="https://velog.io/@lasid84/%EC%9B%B9-%EA%B8%B0%EB%B0%98-%ED%86%B5%ED%95%A9%EC%8B%9C%EC%8A%A4%ED%85%9C-%EA%B5%AC%EC%B6%95-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%ED%86%B5%ED%95%A9%EA%B3%BC-%EC%B5%9C%EC%A0%81%ED%99%94-%EA%B2%BD%ED%97%98-%EA%B3%B5%EC%9C%A0" target="_blank">웹 기반 통합 시스템</a>으로 전환해 중복 업무를 크게 감소시킴</li>
            <li>글로벌 시스템 연동을 위한 <a href="https://velog.io/@사용자명" target="_blank">스크래핑 시스템</a> 설계 및 구축</li>
            <li>PostgreSQL 성능 튜닝 및 장애 대응</li>
            <li>코드리뷰 & 아키텍처 개선 등 개발환경 개선</li>
          </ul>

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 일진글로벌
        link: www.iljin.com
        link_text: www.iljin.com
        sub_title: C# & .Net개발자
        caption: 2010.12 ~ 2021.12
        quote: >
          연매출 1조 314억원의 베어링 제조기업
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>VB6/Oracle 기반 MES 레거시 <strong>분석∙파악</strong> 후, <strong>C# & .NET으로 재개발</strong> 및 <strong>SAP 연동 자동화</strong> 구축</li>
            <li>슬로바키아 공장 MES 업그레이드(VB6 → C# .NET) <strong>프로젝트 팀 리드</strong>를 맡아, 한국 본사 및 현지 인력들과의 <strong>일정∙이슈 조율</strong> 및 개발 총괄</li>
            <li>통계적 공정관리 이상현상 알림 시스템 개발(일 평균 100만 건 데이터 실시간 분석)</li>
            <li>2017년 본부 추천 과장 <span class="highlight-black">특진</span></li>
            <li>2021년 <span class="highlight-black">우수사원</span> 표창</li>
          </ul>

  - title: 역량
    layout: list
    content: #| # this will include new lines to allow paragraphs
      - title: 개발 파트 매니징
        layout: top-middle
        quote: |
        description: |
          <ul>
            <li><a href="https://velog.io/@lasid84/%EC%9B%B9%ED%86%B5%ED%95%A9-%EC%B5%9C%EC%A0%81%ED%99%94" target="_blank">웹 기반 사내 통합 시스템 구축 프로젝트 전체 리드 (2023.09 ~ 현재)</a></li>     
            <li><a href="https://velog.io/@사용자명" target="_blank">RPA 프로젝트 전체 리드</a> (2024.08 ~ 2024.12)</li>
            <li><a href="https://velog.io/@사용자명" target="_blank">회계 프로그램 리뉴얼 전체 리드</a> (2023.01 ~ 2023.07)</li>   
            <li>국내 8개 법인 운반비 전산화 프로젝트 전체 리드 (2020.04 ~ 2020.12)</li>
            <li>국내외 MES시스템 리뉴얼 및 SAP연동 프로젝트 개발파트 리드 (2019.01 ~ 2019.12)</li>
          </ul>

      - title: 레거시 시스템 리팩토링/리엔지니어링
        layout: top-middle
        quote: |
        description: |
          <ul>
            <li>파편화 된 사내 시스템(C#,VB6, Oracle Forms, React => TS & NextJS & Express) 마이그레이션 (2023.09 ~ 현재)</li>     
            <li>DBMS(Oracle, MySQL, PostgreSQL => PostgreSQL) 마이그레이션 (2023.01 ~ 2023.07)</li>   
            <li>MES시스템(VB6 => C#) 리뉴얼 및 SAP연동 (2019.01 ~ 2019.12)</li>
          </ul>

      - title: 대용량 데이터 처리 및 성능 개선
        layout: top-middle
        quote: |
        description: |
          <ul>
            <li>DBMS 프로시저 형상관리 및 Slow Query 알람 시스템 구축(2024.09 ~ 2024.12)</li>   
            <li>약 1000만건 데이터 마이그레이션 및 Slow Query 튜닝</li>     
            <li>일 100만 건 이상의 SPC 측정 데이터 처리 프로그램 개발</li>
          </ul>

      - title: 견고한 데이터 구조 및 애플리케이션 설계
        layout: top-middle
        quote: |
        description: |
          <ul>
            <li>일 20만건의 외부 데이터 스크래핑 처리</li>   
            <li><a href="https://velog.io/@lasid84/API-%EC%84%9C%EB%B2%84 target="_blank">성능∙확장성∙유지보수성 고려한 아키텍처 구성</a></li>
          </ul>

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Backend
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>NodeJS & TypeScript, Express</li>
            <li>Puppeteer, Proxy, Reflect</li>
            <li>.NET(C#, 4.5, 6), WCF/gRPC</li>
            <li>Oracle, PostgreSQL, MySQL</li>
          </ul>
      
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>TurboRepo, pnpm, Worker Threads, PM2</li>
            <li>Windows Server, Linux CentOS</li>
            <li>Nginx</li>
          </ul>

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Frontend(Web & Desktop)
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>React(Next.js) & TypeScript, Zustand</li>
            <li>Windows Forms(C#)</li>
          </ul>

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: (주)케이더블유이코리아
  #       link: https://www.kwe.com/
  #       link_text: www.kwe.com
  #       sub_title: 풀스택 개발자
  #       caption: 2022.01 ~ 현재
  #       quote: >
  #         연매출 2,634억원의 국제 종합 물류기업
  #       description: | # this will include new lines to allow paragraphs
  #         <ul>
  #           <li><strong>10종의 레거시 시스템 및 3종의 DBMS</strong>를 분석∙파악 후 <a href="https://velog.io/@사용자명" target="_blank">웹 기반 통합 시스템</a>으로 전환해 중복 업무를 크게 감소시킴</li>
  #           <li>글로벌 시스템 연동을 위한 <a href="google.com">스크래핑 시스템</a> 설계 및 구축</li>
  #           <li>PostgreSQL 성능 튜닝 및 장애 대응</li>
  #           <li>코드리뷰 & 아키텍처 개선 등 개발환경 개선</li>
  #         </ul>


  # <div class="layout-top-middle details"><h4>레거시 개발 파트 매니징 / 프로젝트 리드</h4>
  #   <a href="https://www.notion.so/5badc2ba03904832bce8fdf3dc4a407b" target="_blank" class="link">https://www.notion.so/5badc2ba03904832bce8fdf3dc4a407b</a>
  #   <p class="quote">2022.01.17 ~ 현재</p>
  # </div>
  # <li>2021년 <span class="highlight-black">우수사원</span> 표창</li>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
